// Auth
export const AUTH_USER_START = 'AUTH_USER_START';
export type  AUTH_USER_START =  typeof AUTH_USER_START;

export const AUTH_USER_STOP = 'AUTH_USER_STOP';
export type  AUTH_USER_STOP =  typeof AUTH_USER_STOP;

export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export type  AUTH_USER_SUCCESS =  typeof AUTH_USER_SUCCESS;

export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
export type  AUTH_USER_FAILED =  typeof AUTH_USER_FAILED;

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type  LOGIN_SUCCESS =  typeof LOGIN_SUCCESS;

export const LOGIN_FAILED = 'LOGIN_FAILED';
export type  LOGIN_FAILED =  typeof LOGIN_FAILED;

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export type  SIGNUP_SUCCESS =  typeof SIGNUP_SUCCESS;

export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export type  SIGNUP_FAILED =  typeof SIGNUP_FAILED;

export const LOGOUT = 'LOGOUT';
export type  LOGOUT =  typeof LOGOUT;


// User
export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export type  UPDATE_PROFILE_START =  typeof UPDATE_PROFILE_START;

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export type  UPDATE_PROFILE_SUCCESS =  typeof UPDATE_PROFILE_SUCCESS;

export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
export type  UPDATE_PROFILE_FAILED =  typeof UPDATE_PROFILE_FAILED;

export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export type  UPLOAD_AVATAR_SUCCESS =  typeof UPLOAD_AVATAR_SUCCESS;

export const UPLOAD_AVATAR_FAILED = 'UPLOAD_AVATAR_FAILED';
export type  UPLOAD_AVATAR_FAILED =  typeof UPLOAD_AVATAR_FAILED;

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export type  CHANGE_PASSWORD_SUCCESS =  typeof CHANGE_PASSWORD_SUCCESS;

export const CHANGE_PASSWORD_FAILED =  'CHANGE_PASSWORD_FAILED';
export type  CHANGE_PASSWORD_FAILED =   typeof CHANGE_PASSWORD_FAILED;

export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export type  DELETE_ACCOUNT_SUCCESS =  typeof DELETE_ACCOUNT_SUCCESS;

export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED';
export type  DELETE_ACCOUNT_FAILED =  typeof DELETE_ACCOUNT_FAILED;